name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Configure clasp with Service Account
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > service-account-key.json
          npx @google/clasp login --no-localhost --creds service-account-key.json
          npx @google/clasp status

      - name: Push to Google Apps Script
        run: npx @google/clasp push -f
