name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Decrypt Service Account Key
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > service-account-key.json

      - name: Configure clasp with Service Account
        run: |
          clasp login --oauth2 --json service-account-key.json
          clasp status

      - name: Push to Google Apps Script
        run: clasp push -f
